---
# tasks file for ansible-role-apache
#  tasks:
    - name: Installs apache web server
      yum:
        name: httpd
        state: latest
        update_cache: true
    - name: ensure apache is running (and enable it at boot)
      service:
        name: httpd
        state: started
        enabled: yes
    - name : make Apache listen on 8080 port
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen (\d+)$'
        replace: 'Listen {{http_port}}'
      notify:
        - restart apache
